variables:
  PLUGIN: 'tool_userrestore'
  PATHNAME: 'admin/tool/userrestore'
  REPOURL: 'https://github.com/sebsoftnl/moodle-tool_userrestore'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
